BBS.WebUI/Controllers/BoardController.cs
using BBS.Domain.Entities;
using BBS.Service.BusinessInterfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BBS.WebUI.Controllers
{
    public class BoardController : Controller
    {

        private IBoardService boardService = null;
        //
        // GET: /Board/

        public BoardController(IBoardService boardService)
        {
            this.boardService = boardService;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ChildBoards(int boardID)
        {
            IEnumerable<Board> childBoards = boardService.GetChildBoards(boardID);
            return View(childBoards);
        }

    }
}

BBS.WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BBS.WebUI.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }
    }
}

BBS.WebUI/Views/Home/Index.cshtml
@using BBS.Domain.Entities

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_BasicLayout.cshtml";
}

<script type="text/javascript">
    $(document).ready(function () {
        $('.slider').slider({ full_width: true });
    });
</script>

<div class="slider container">
    <ul class="slides">
        <li>
            <img src="~/Content/images/s1.jpg"> <!-- random image -->
            <div class="caption center-align">
                <h3>This is our big Tagline!</h3>
                <h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
            </div>
        </li>
        <li>
            <img src="~/Content/images/s2.jpg"> <!-- random image -->
            <div class="caption left-align">
                <h3>Left Aligned Caption</h3>
                <h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
            </div>
        </li>
        <li>
            <img src="~/Content/images/s3.jpg"> <!-- random image -->
            <div class="caption right-align">
                <h3>Right Aligned Caption</h3>
                <h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
            </div>
        </li>
        <li>
            <img src="~/Content/images/s2.jpg"> <!-- random image -->
            <div class="caption center-align">
                <h3>This is our big Tagline!</h3>
                <h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
            </div>
        </li>
    </ul>
</div>

@if (Session["User"] == null)
{
    <div class="divider"></div>
    <div class="row">
        <div class="col s2 offset-s2">
            <a class="waves-effect waves-light btn-large" href="/User/SignUp"><i class="mdi-action-account-child right"></i>SignUp</a>
        </div>
        <div class="col s2 offset-s4">
            <a class="waves-effect waves-light btn-large" href="/User/Login"><i class="mdi-action-home right"></i>Login</a>
        </div>
    </div>
    <div class="divider"></div>
}

<div class="row">
    <a href="~/User/AdminIndex">进入管理员页面</a>
</div>

<div class="container">
    <div class="row">
        @{
            IEnumerable<Board> rootBoards = ViewBag.RootBaords;
            foreach (Board board in rootBoards)
            {
                <div class="col s6 m6">
                    <div class="card">
                        <div class="card-image">
                            <img src="~/Content/images/sample-1.jpg"/>
                            <span class="card-title">@board.Name</span>
                        </div>
                        <div class="card-content">
                            <p>@board.Description</p>
                        </div>
                        <div class="card-action">
                            <a href="@Url.Action("ChildBoards", "Board", new { boardID = board.ID})">进入板块</a>
                            <a href="#">进入板块</a>
                        </div>
                    </div>
                </div>
            }
        }
    </div>
</div>